#!/bin/bash

# trap 'service postgresql stop' EXIT

sudo -iu postgres -- sh -c "$INSTALL_DIR/bin/gtm_ctl start -D /data/gtm -Z gtm -l $LOG_DIR/gtm.log"
sudo -iu postgres -- sh -c "$INSTALL_DIR/bin/pg_ctl start -D /data/datanode1 -Z datanode -l $LOG_DIR/datanode1.log"
sudo -iu postgres -- sh -c "$INSTALL_DIR/bin/pg_ctl start -D /data/datanode2 -Z datanode -l $LOG_DIR/datanode2.log"
sudo -iu postgres -- sh -c "$INSTALL_DIR/bin/pg_ctl start -D /data/coord1 -Z coordinator -l $LOG_DIR/coord1.log"

tail -f $LOG_DIR/*.log
wait
